services:
  bling-mvp:
    build: .
    container_name: bling-mvp
    ports:
      - "3004:3004"
    volumes:
      - ./data:/data
    restart: unless-stopped
    networks:
      - proxy_public

networks:
  proxy_public:
    external: true
